@startuml

title 文件数据存储架构

node 文件数据{

}
node 集合数据
node 序列文件数据

folder 文件数据目录{
    folder 规格目录{
        file 文件版本1软连接
        file 文件版本2软连接
        file 文件版本3软连接

        folder 阶段目录1{
            file 1当前文件版本
            file 1其他版本
        }
        folder 阶段目录2{
            file 2当前版本
            file 2其他版本
        }
        folder 阶段目录3{
            file 3当前版本
            file 3其他版本
        }
    }
}

folder 集合数据目录{
    folder 规格目录{
        file 集合阶段1软连接
        file 集合版本2软连接
        file 集合版本3软连接

        folder 阶段目录1{
            folder 1当前集合版本
            folder 1其他集合版本
        }
        folder 阶段目录2{
            folder 2当前集合版本
            folder 2其他集合版本
        }
        folder 阶段目录3{
            folder 3当前集合版本
            folder 3其他集合版本
        }
    }
}

文件数据 --- 文件数据目录
文件版本1软连接 ---> 1当前文件版本
文件版本2软连接 ---> 2当前版本
文件版本3软连接 ---> 3当前版本

集合数据 <- 序列文件数据
集合数据 --- 集合数据目录
集合阶段1软连接 ---> 1当前集合版本
集合版本2软连接 ---> 2当前集合版本
集合版本3软连接 ---> 3当前集合版本
@enduml