@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 服务端: 文件上传首个包,包含文件信息,不包含文件数据块
服务端 -> 数据系统: 文件上传请求, 文件信息

数据系统 -> 数据系统: 根据文件信息取得文件接收器(主要根据文件大小分组)
数据系统 -> 数据系统: 检查文件上传状态是否存在(续传), 更新上传状态
数据系统 -> 数据系统: 检查存储空间是否足够
数据系统 -> 数据系统: 创建文件
数据系统 -> 服务端: 文件接收器

服务端 -> 服务端: 建立接收数据流通道

loop 交互式递增校验式接收数据，保证数据完整性
服务端 --> 服务端: 检查是否需要续传并取得续传编号
服务端 --> 客户端: 下一个数据块的编号
客户端 -> 服务端: 发送对应编号的数据块
服务端 -> 服务端: 校验数据块,写入数据流通道
alt 校验通过
客户端 <-- 服务端: 下一个数据块的编号
else 校验没通过
服务端 --> 客户端: 本次数据块的编号
end
    break 数据已经发送完
    客户端 -> 服务端: 发送编号为0的数据块，表示已经发送完了
    end
end

服务端 -> 服务端: 校验文件


alt 校验通过
服务端 --> 客户端:  0表示接收完成
else 校验没通过
服务端 --> 客户端:  -1文件表示校验失败,
end

客户端 -> 服务端: 关闭发送流
服务端 -> 数据系统: 关闭数据流通道
数据系统-> 数据系统: 写入缓存, 关闭文件流
数据系统 -> 数据系统: 删除续传记录文件，如果存在
数据系统 -> 数据系统: 创建版本连接
@enduml
