@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 服务端: 根据数据编号和数据阶段取得文件信息
服务端 -> 客户端: 文件信息

alt 内网
客户端 -> 数据系统: 根据路径读取文件
end

客户端 -> 服务端: 双向流对话式下载文件请求
服务端 -> 数据系统: 取得文件读取流
服务端  -> 客户端: 发送文件数据流

loop 交互式递增校验式接收数据，保证数据完整性
客户端 -> 服务端: 请求下载数据块
服务端 -> 客户端: 发送对应数据块
客户端 -> 客户端: 校验数据块
客户端 -> 客户端: 写入缓存
客户端 -> 客户端: 记录下载状态

alt 校验通过
服务端 <-- 客户端: 下一个数据块
else 校验没通过
客户端 --> 服务端 : 本次数据块的编号
end
    break 数据已经发送完
    服务端 -> 客户端: 发送编号为0的返回包，表示已经发送完了
    end
end

客户端 -> 客户端: 校验文件


客户端 -> 客户端: 缓存写入文件并关闭连接
@enduml