@startuml

title 文件数据存储架构

database 规格数据库
database 数据数据库[
    数据数据库
    ==
    持有specs_id
]
database 阶段数据库[
    阶段数据库
    ==
    持有data_id
]
database 版本数据库[
    版本数据库
    ==
    持有stage_id
    持有文件表
]

folder 规格目录{
    folder 数据目录{
        folder 阶段目录{
            file 默认版本连接
            folder 版本目录{
                file 文件数据
                folder 集合
                folder 序列
            }
            folder 1其他版本
        }
    }
}

规格数据库 --> 规格目录
数据数据库 --> 数据目录
阶段数据库 --> 阶段目录
版本数据库 --> 版本目录

数据数据库 -> 规格数据库
阶段数据库 -> 数据数据库
版本数据库 -> 阶段数据库
默认版本连接 --> 文件数据
默认版本连接 --> 集合
默认版本连接 --> 序列
@enduml