@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 客户端 : 取得环境，判断是否在内网

客户端 -> 数据系统 : 添加文件请求
alt 文件在内网:
    客户端 -> 数据系统 : 上传文件信息
    数据系统 -> 数据系统 : 检查文件信息
    数据系统 -> 数据系统 : 生成文件索引
else 文件在外网:
    客户端 -> 数据系统 : 上传文件
    数据系统 -> 数据系统 : 检查文件信息
    数据系统 -> 数据系统 : 生成文件索引
end
    数据系统 -> 客户端 : 添加结果
@enduml